<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adress' => [parent::class, 'adress', null, 16],
        "\0".parent::class."\0".'birth_date' => [parent::class, 'birth_date', null, 16],
        "\0".parent::class."\0".'books' => [parent::class, 'books', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'first_name' => [parent::class, 'first_name', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'last_name' => [parent::class, 'last_name', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'update_at' => [parent::class, 'update_at', null, 16],
        "\0".parent::class."\0".'zip_code' => [parent::class, 'zip_code', null, 16],
        'adress' => [parent::class, 'adress', null, 16],
        'birth_date' => [parent::class, 'birth_date', null, 16],
        'books' => [parent::class, 'books', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'first_name' => [parent::class, 'first_name', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'last_name' => [parent::class, 'last_name', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'update_at' => [parent::class, 'update_at', null, 16],
        'zip_code' => [parent::class, 'zip_code', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
