<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEcNRnXE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEcNRnXE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEcNRnXE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEcNRnXE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEcNRnXE\App_KernelDevDebugContainer([
    'container.build_hash' => 'EcNRnXE',
    'container.build_id' => 'c68aa410',
    'container.build_time' => 1761921994,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEcNRnXE');
