<?php

namespace ContainerEcNRnXE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VtsTxgUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vtsTxgU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vtsTxgU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\DefaultController::delete' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\DefaultController::edit' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\DefaultController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\DefaultController::newLoan' => ['privates', '.service_locator.Lo.9W7k', 'get_ServiceLocator_Lo_9W7kService', true],
            'App\\Controller\\DefaultController::newUser' => ['privates', '.service_locator.gxkSA7l', 'get_ServiceLocator_GxkSA7lService', true],
            'App\\Controller\\DefaultController::show' => ['privates', '.service_locator.KJSb96P', 'get_ServiceLocator_KJSb96PService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\DefaultController:delete' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\DefaultController:edit' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\DefaultController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\DefaultController:newLoan' => ['privates', '.service_locator.Lo.9W7k', 'get_ServiceLocator_Lo_9W7kService', true],
            'App\\Controller\\DefaultController:newUser' => ['privates', '.service_locator.gxkSA7l', 'get_ServiceLocator_GxkSA7lService', true],
            'App\\Controller\\DefaultController:show' => ['privates', '.service_locator.KJSb96P', 'get_ServiceLocator_KJSb96PService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\DefaultController::delete' => '?',
            'App\\Controller\\DefaultController::edit' => '?',
            'App\\Controller\\DefaultController::new' => '?',
            'App\\Controller\\DefaultController::newLoan' => '?',
            'App\\Controller\\DefaultController::newUser' => '?',
            'App\\Controller\\DefaultController::show' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\DefaultController:delete' => '?',
            'App\\Controller\\DefaultController:edit' => '?',
            'App\\Controller\\DefaultController:new' => '?',
            'App\\Controller\\DefaultController:newLoan' => '?',
            'App\\Controller\\DefaultController:newUser' => '?',
            'App\\Controller\\DefaultController:show' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
